/**:
  ros__parameters:
    frame_id: "map"
    pose_frame_id: ""
    lookahead_distance: 1.0
    cmd_vel_distance_rate: 0.2
    vel_limit:
      linear:
        x: 1.0
        y: .inf
        z: .inf
      angular:
        x: .inf
        y: .inf
        z: 1.0
    accel_limit:
      linear:
        x: 2.0
        y: .inf
        z: .inf
      angular:
        x: .inf
        y: .inf
        z: 2.0
    cmd_vel_timeout: 10.0
    robot:
      x_min: -0.75
      x_max: 0.75
      y_min: -0.35
      y_max: 0.35
      z_min: 0.1
      z_max: 1.5
