/**:
  ros__parameters:
    frame_id: "map"
    purepursuit:
      lookahead_distance: 3.0
    follow_point:
      vel_per_distance: 0.1
      margin_distance: 1.0
    obstacle_speed_limitter:
      speed_per_distance: 0.1
      offset_distance: 1.0
    robot:
      width: 0.7
      min_turning_radius: 1.5
    lidar:
      min_distance: 0.4
      obstacle:
        z_min: -1.0
        z_max: 0.0
    vel_limit:
      linear:
        x: 0.2
        y: .inf
        z: .inf
      angular:
        x: .inf
        y: .inf
        z: 0.2
    accel_limit:
      linear:
        x: 1.0
        y: .inf
        z: .inf
      angular:
        x: .inf
        y: .inf
        z: 1.0
    cmd_vel_timeout: 10.0
    cmd_vel_limit_rate: 60.0
    qos_overrides:
      $(var pose_topic_name):
        subscription:
          depth: 10
          history: keep_last
          reliability: best_effort
      $(var namespace)/$(var controller_name)/pose/transformed:
        publisher:
          depth: 10
          history: keep_last
          reliability: best_effort
        subscription:
          depth: 10
          history: keep_last
          reliability: best_effort
      $(var global_plan_topic_name):
        subscription:
          depth: 10
          history: keep_last
          reliability: reliable
          durability: transient_local
      $(var namespace)/$(var controller_name)/global_plan/transformed:
        publisher:
          depth: 10
          history: keep_last
          reliability: reliable
          durability: transient_local
        subscription:
          depth: 10
          history: keep_last
          reliability: reliable
          durability: transient_local
      $(var namespace)/$(var controller_name)/local_plan:
        publisher:
          depth: 10
          history: keep_last
          reliability: reliable
          durability: transient_local
        subscription:
          depth: 10
          history: keep_last
          reliability: reliable
          durability: transient_local
      $(var lidar_points_topic_name):
        subscription:
          depth: 10
          history: keep_last
          reliability: reliable
      $(var namespace)/$(var controller_name)/vel_limit:
        publisher:
          depth: 10
          history: keep_last
          reliability: best_effort
        subscription:
          depth: 10
          history: keep_last
          reliability: best_effort
      ${var accel_limit_topic_name}:
        subscription:
          depth: 10
          history: keep_last
          reliability: reliable
          durability: volatile
      $(var namespace)/$(var controller_name)/cmd_vel_nav:
        publisher:
          depth: 10
          history: keep_last
          reliability: best_effort
        subscription:
          depth: 10
          history: keep_last
          reliability: best_effort
      $(var cmd_vel_topic_name):
        publisher:
          depth: 10
          history: keep_last
          reliability: reliable
      $(var namespace)/$(var controller_name)/target_point:
        publisher:
          depth: 10
          history: keep_last
          reliability: reliable